# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('shorttext', models.CharField(max_length=2000)),
                ('fulltext', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='OrdinaryNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('shorttext', models.CharField(max_length=2000)),
                ('fulltext', models.CharField(max_length=10000)),
            ],
        ),
    ]
