# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_importantnews_ordinarynews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BodyOfImportantNews',
        ),
        migrations.DeleteModel(
            name='BodyOfOrdinaryNews',
        ),
        migrations.DeleteModel(
            name='TitleOfImportantNews',
        ),
        migrations.DeleteModel(
            name='TitleOfOrdinaryNews',
        ),
    ]
