# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20161011_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfplSeazon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstteam', models.CharField(max_length=200)),
                ('secondteam', models.CharField(max_length=200)),
                ('dateofmatch', models.DateTimeField()),
            ],
        ),
    ]
