# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-12 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_rfplseazon'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('shorttext', models.CharField(max_length=2000)),
                ('fulltext', models.CharField(max_length=10000)),
                ('type_of_news', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ImportantNews',
        ),
        migrations.DeleteModel(
            name='OrdinaryNews',
        ),
    ]
