# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_news_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.CharField(choices=[('n', ''), ('football', models.ImageField(default='../core/static/img/button.png', upload_to='../core/static/img/visual1.jpg')), ('hockey', models.ImageField(default='../core/static/img/button.png', upload_to='../core/static/img/visual2.png'))], default='n', max_length=200),
        ),
    ]
