# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_news_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.ImageField(upload_to='../core/static/img/'),
        ),
    ]
