# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_remove_news_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.SmallIntegerField(choices=[(0, ''), (1, '\u0424\u0443\u0442\u0431\u043e\u043b'), (2, '\u0425\u043e\u043a\u043a\u0435\u0439')], default=0),
        ),
    ]
