# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-18 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_auto_20161018_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(choices=[('', ''), ('\u0424\u0443\u0442\u0431\u043e\u043b', '\u0424\u0443\u0442\u0431\u043e\u043b'), ('\u0425\u043e\u043a\u043a\u0435\u0439', '\u0425\u043e\u043a\u043a\u0435\u0439')], default='', max_length=200),
        ),
    ]
